name: lj_loadding_empty
description: lj_loadding_empty support loadding by loaddingdata status.
version: 1.1.1
homepage: https://github.com/JamesBondMine/lj_loadding_empty

environment:
  sdk: '>=2.19.2 <3.0.0'
  # flutter: ">=2.0.0"

dependencies:
  flutter:
      sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0



flutter:
  uses-material-design: true
  assets:
    - packages/lj_loadding_empty/assets/images/NullstatusEmpty.png
